# buildspec.yml

version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Running unit tests...
      - python -m unittest discover -s tests
  build:
    commands:
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Build and tests successful
